Arrays

In [ ]:
import numpy

def arrays(arr):
    return numpy.array(arr[::-1],float)

arr = input().strip().split()
result = arrays(arr)
print(result)

Shape and Reshape

In [3]:
import numpy as np
arr = np.array(input().split(),int)
print(arr.reshape(3,3))

5 2 4 6 5 8 6 4


np-transpose-and-flatten

In [1]:
import numpy as np
a=int(input().split()[0])
arr = np.array([input().strip().split() for _ in range(a)], int)
print(arr.transpose())
print(arr.flatten())

0 1


np-concatenate

In [5]:
import numpy as np
n=list(map(int,input().split()))
arr= np.array([input().strip().split() for _ in range(n[0]+n[1])],int)
print(arr)

1 2
1 2
2 3
2 5
[[1 2]
 [2 3]
 [2 5]]


Zeros and Ones

In [9]:
import numpy as np
n= list(map(int,input().split()))
print(np.zeros(n, dtype=np.int))
print(np.ones(n, dtype=np.int))

array([[0., 0., 0.],
       [0., 0., 0.],
       [0., 0., 0.]])

Eye and Identity

In [ ]:
import numpy
numpy.set_printoptions(legacy='1.13')
n=list(map(int,input().split()))
print(numpy.eye(n[0],n[1]))

Array Mathematics

In [15]:
import numpy
_ = input()
arr= np.array([input().strip().split() for i in range(2)],int)
print(arr[0]+arr[1])

1 2
1 2 3 4
5 6 7 8
[ 6  8 10 12]


Array Mathematics

In [ ]:
import numpy as np
n,m = list(map(int, input().split()))
a = np.array([input().split() for _ in range(n)], int)
b = np.array([input().split() for _ in range(n)], int)
print(a+b)
print(a-b)
print(a*b)
print(a//b)
print(a%b)
print(a**b)

Floor, Ceil and Rint

In [ ]:
import numpy as np
np.set_printoptions(legacy='1.13')
arr = np.array(input().split(), float)
print(np.floor(arr))
print(np.ceil(arr))
print(np.rint(arr))

Sum and Prod

In [9]:
import numpy as np
n,m=list(map(int,input().split()))
b=1
arr=np.array([input().split() for _ in range(m)],int)
arr=np.sum(arr,axis=0)
for i in arr:
    b=b*i
print(b)

2 2
1 4
2 5
12


Min ad Max

In [ ]:
import numpy as np
n,m=list(map(int,input().split()))
arr=np.array([input().split() for _ in range(m)],int)
arr=np.min(arr,axis=1)
print(np.max(arr))

Mean, Var, and Std

In [ ]:
import numpy as np
n,m=list(map(int,input().split()))
arr=np.array([input().split() for _ in range(m)],int)
print(np.mean(arr,axis=1))
print(np.var(arr,axis=0))
print(round(np.std(arr),11))

Dot and Cross

In [11]:
import numpy as np
n=int(input())
a=np.array([input().split() for _ in range(n)],int)
b=np.array([input().split() for _ in range(n)],int)
print(np.dot(a,b))

2
4 5
7 8
8 2
1 9
[[4 5]
 [7 8]]
[[8 2]
 [1 9]]


Inner and Outer

In [ ]:
import numpy as np
a=np.array(input().split(),int)
b=np.array(input().split(),int)
print(np.inner(a,b),np.outer(a,b),sep='\n')

Polynomials

In [17]:
import numpy as np
x=list(map(float,input().split()))
y=int(input())
x=x[::-1]
s=0
for i in range(len(x)):
    s=s+x[i]*y**i
print(s)

2 3 4 5 6
[6.0, 5.0, 4.0, 3.0, 2.0]


Linear Algebra

In [ ]:
import numpy as np
n= int(input())
arr=np.array([input().split() for _ in range(n)],float)
print(round(np.linalg.det(arr),2))